# Generated by Django 2.1 on 2018-08-10 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255, unique=True)),
                ('report', models.CharField(max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('cure_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='accounts.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PredictDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_disease_name', models.CharField(max_length=255, unique=True)),
                ('request_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicts', to='symptoms.Disease')),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='symptoms.Symptom'),
        ),
    ]
