# Generated by Django 2.1 on 2018-08-13 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180811_0058'),
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('cure_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseasereport', to='accounts.Doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='disease',
            name='cure_by',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='report',
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseasereport', to='symptoms.Disease'),
        ),
    ]
